services:
  - type: web
    name: compiler-backend
    env: docker
    plan: free
    dockerCommand: npm start
    branch: main
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
